SET FOREIGN_KEY_CHECKS=0

DROP TABLE IF EXISTS `DICTIONARY_DETAIL` CASCADE
;

CREATE TABLE `DICTIONARY_DETAIL`
(
	`ID` VARCHAR(36) NOT NULL,
	`DICT_ID` VARCHAR(36) NOT NULL,
	`DICT_DET_NAME` VARCHAR(32),
	`DICT_DET_CODE` VARCHAR(32),
	`CREATED_DATE` DATE,
	`CREATED_USER` VARCHAR(32),
	`UPDATED_DATE` DATE,
	`UPDATED_USER` VARCHAR(32),
	CONSTRAINT `PK_DICTIONARY_DETAIL` PRIMARY KEY (`ID`,`DICT_ID`)
)
;

SET FOREIGN_KEY_CHECKS=1

SET FOREIGN_KEY_CHECKS=0

DROP TABLE IF EXISTS `DICTIONARY` CASCADE
;

CREATE TABLE `DICTIONARY`
(
	`ID` VARCHAR(36) NOT NULL,
	`DICT_NAME` VARCHAR(32),
	`DICT_CODE` VARCHAR(32),
	`REMARK` VARCHAR(256),
	`STATUS` VARCHAR(2),
	`CREATED_DATE` DATE,
	`CREATED_USER` VARCHAR(32),
	`UPDATED_DATE` DATE,
	`UPDATED_USER` VARCHAR(32),
	CONSTRAINT `PK_DICTIONARY` PRIMARY KEY (`ID`)
)
;

SET FOREIGN_KEY_CHECKS=1
